"""
Django settings for gestor_eventos project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Defino la ruta base del proyecto
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Configuraciones rápidas de desarrollo - no aptas para producción
# Ver https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# ADVERTENCIA DE SEGURIDAD: Mantén la clave secreta utilizada en producción en secreto.
SECRET_KEY = 'django-insecure-k1xn8%zj+a6)kmt)qh03a03yl3n^h41_+@2jofgq+#@l74*g#$'

# ADVERTENCIA DE SEGURIDAD: No ejecutes con el debug activado en producción.
DEBUG = True

# Lista de hosts permitidos para acceder a la aplicación
ALLOWED_HOSTS = []

# Definición de aplicaciones instaladas
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',  # Aplicación personalizada para la gestión de usuarios
    'eventos',  # Aplicación personalizada para la gestión de eventos
    'inscripciones',  # Aplicación personalizada para la gestión de inscripciones
]

# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Configuración de la URL principal
ROOT_URLCONF = 'gestor_eventos.urls'

# Configuración de las plantillas
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Incluye la carpeta 'templates' del proyecto principal
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Configuración de la aplicación WSGI
WSGI_APPLICATION = 'gestor_eventos.wsgi.application'

# Configuración de la base de datos
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # Utilizo PostgreSQL como motor de base de datos
        'NAME': 'db_gestor_eventos',  # Nombre de la base de datos
        'USER': 'postgres',  # Usuario de la base de datos
        'PASSWORD': 'davidloor076',  # Contraseña de la base de datos
        'HOST': 'localhost',  # Host de la base de datos
        'PORT': '5432',  # Puerto de la base de datos
    }
}

# Validadores de contraseñas
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  # Validador de similitud de atributos
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  # Validador de longitud mínima
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',  # Validador de contraseñas comunes
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',  # Validador de contraseñas numéricas
    },
]

# Internacionalización
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = 'en-us'  # Código de idioma

TIME_ZONE = 'UTC'  # Zona horaria

USE_I18N = True  # Habilitar la internacionalización

USE_TZ = True  # Usar zona horaria

# Archivos estáticos (CSS, JavaScript, Imágenes)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_URL = 'static/'  # URL de archivos estáticos

# Tipo de campo de clave primaria predeterminado
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Modelo de usuario personalizado
AUTH_USER_MODEL = 'usuarios.Usuario'

# URL de inicio de sesión
LOGIN_URL = 'login'

# Redirección después de iniciar sesión
LOGIN_REDIRECT_URL = 'lista_eventos'

# Redirección después de cerrar sesión
LOGOUT_REDIRECT_URL = 'login'

# Directorios de archivos estáticos
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
